# Pair programming Numpy

## Creación y Indexación:

In [1]:
# en primer lugar, importamos la libreria para poder trabajar con NUMPY
import numpy as np

1. Crea un array 1D con 50 valores aleatorio del 10 al 99. Accede a los elementos en las posiciones múltiplos de 5.

In [2]:
array1 = np.random.randint (10,100, (50))
array1

array([67, 61, 90, 18, 87, 74, 46, 83, 90, 38, 81, 28, 70, 18, 39, 69, 35,
       44, 98, 45, 26, 30, 46, 27, 14, 68, 23, 88, 90, 85, 39, 46, 93, 74,
       51, 92, 68, 44, 54, 23, 18, 85, 69, 91, 82, 92, 11, 56, 35, 89])

In [3]:
array1[::5]


array([67, 74, 81, 69, 26, 68, 39, 92, 18, 92])

2. Crea un array 1D con 30 valores del 1 al 20 (ambos incluidos). Utiliza indexación para obtener los elementos en las posiciones impares.

In [4]:
array2 = np.random.randint (1,21,(30))
array2

array([17, 13, 19, 13,  5,  5, 13, 14,  8,  7, 20,  6, 20,  1,  3,  2, 13,
       12, 11,  1,  7,  7, 13,  9,  5,  3,  7, 20,  4, 15])

In [5]:
array2[1::2]

array([13, 13,  5, 14,  7,  6,  1,  2, 12,  1,  7,  9,  3, 20, 15])

3. Crea un array 2D de forma (4, 6) con números aleatorios decimales (no deben estar comprendidos solo entre 0 y 1). Accede a la última fila de la matriz. Los decimales deben estar redondeados a 2 decimales.

In [6]:
array3 = np.round(np.random.uniform(1, 9, (4, 6)), decimals=2)
array3

array([[8.4 , 3.17, 7.3 , 2.55, 5.98, 1.78],
       [2.2 , 7.19, 2.39, 2.18, 7.01, 2.26],
       [3.24, 2.65, 8.63, 4.35, 7.  , 2.31],
       [5.19, 5.97, 5.2 , 6.44, 5.33, 7.9 ]])

In [7]:
array3 [-1]

array([5.19, 5.97, 5.2 , 6.44, 5.33, 7.9 ])

4. Crea un array NumPy 2D de forma (6, 4) con valores decimales entre 0 y 1. Accede a la segunda columna de la matriz. Los números deben estar redondeados a 2 decimales.

In [8]:
array4 = np.round(np.random.rand (6,4), decimals = 2)
array4

array([[0.39, 0.73, 0.49, 0.69],
       [0.59, 1.  , 0.92, 0.43],
       [0.37, 0.19, 0.61, 0.73],
       [0.49, 0.46, 0.07, 0.06],
       [0.82, 0.42, 0.21, 0.19],
       [0.39, 0.23, 0.65, 0.53]])

In [9]:
array4[:,1]

array([0.73, 1.  , 0.19, 0.46, 0.42, 0.23])

5. Crea un array 1D con 30 valores enteros aleatorios entre -50 y 50. Extrae los valores negativos.

In [10]:
array5 = np.random.randint (-50, 51, (30))
array5

array([ 21,  -3,   1,  12,   1,   0, -13, -48, -18,   9,   1,  45,  25,
       -45,  50, -29, -24,  43,  -2, -34,  31, -28,  40,  30, -38,  -8,
       -34, -24, -50, -19])

In [11]:
array_negativos = array5[array5 < 0]
array_negativos

array([ -3, -13, -48, -18, -45, -29, -24,  -2, -34, -28, -38,  -8, -34,
       -24, -50, -19])

6. Crea un array 1D con 10 valores entre 0 y 1. Redondea los decimales a 2. Obtén los elementos cuyo valor es mayor que 0.5. ¿En que posición/es están esos elementos?

In [12]:
array6 = np.round (np.random.rand(10), decimals=2)
array6

array([0.13, 0.95, 0.31, 0.97, 0.63, 0.15, 0.85, 0.56, 0.73, 0.71])

In [13]:
array = array6 [array6 >0.5]
array

array([0.95, 0.97, 0.63, 0.85, 0.56, 0.73, 0.71])

7. Crea un array 1D con 40 valores del 1 al 100 (ambos incluidos). Obtén los elementos que son divisibles por 3 y por 4.

In [14]:
array7 = np.random.randint (1,101,(40))
array7

array([68, 90, 16,  8, 14,  8, 93, 76, 49, 69, 66,  1,  6, 27, 31, 99, 94,
       71, 99, 72, 17, 55, 42, 93, 21, 26, 28, 19, 97, 47,  3, 96, 21, 31,
       80,  2, 27, 41, 65, 85])

In [15]:
array_7 = array7 [(array7 %3 == 0) & (array7 &4 == 0)]
array_7

array([90, 66, 27, 99, 99, 72, 42,  3, 96, 27])

8. BONUS: Crea un array 3D de forma (2, 3, 5) y 50 elementos con números enteros entre 0 y 100 (ambos incluidos). Reemplaza los elementos en posiciones múltiplos de 3 por 0.

In [16]:
array8 = np.random.randint (0,101,50)
array8

array([ 8,  8, 37, 85, 11, 45, 47, 86, 22, 23, 19,  4, 89, 44, 18, 17, 92,
       17, 30, 41, 39,  5, 92, 56, 48, 66, 34, 21, 63, 90, 40,  1, 32, 32,
        0, 45, 82, 18, 74, 79, 65, 20,  9,  3, 37, 79,  4, 82,  4, 39])

In [17]:
array8 [array8 %3 == 0 ] = 0

In [18]:
#no es posible hacerlo, porque en un array de dimensiones 2,3,5 sólo caben 30 elementos. Podríamos hacerlo con un array de 30 elementos
reshaped_array = np.reshape (array8, (2,3,5))
reshaped_array

ValueError: cannot reshape array of size 50 into shape (2,3,5)

## Reshape y Transpose:

1. Crea un array 3D de forma (2, 3, 4) con valores aleatorios entre 1 y 100 (ambos inclusive). Utiliza reshape para convertirlo en un array 2D. Deberás pensar en la forma que es correcta para hacer este cambio.

In [ ]:
array_1 = np.random.randint (1,101, (2,3,4))
array_1

array([[[46, 75,  6,  8],
        [90, 19, 22, 35],
        [47, 55,  6, 75]],

       [[67,  7, 98, 14],
        [67, 91, 68, 31],
        [70, 18, 38, 65]]])

In [ ]:
reshaped_array = np.reshape (array_1, (6,4))
reshaped_array

array([[46, 75,  6,  8],
       [90, 19, 22, 35],
       [47, 55,  6, 75],
       [67,  7, 98, 14],
       [67, 91, 68, 31],
       [70, 18, 38, 65]])

In [ ]:
#otra forma de hacerlo sería:
reshaped_array = np.reshape (array_1, (-1,4))
reshaped_array

array([[46, 75,  6,  8],
       [90, 19, 22, 35],
       [47, 55,  6, 75],
       [67,  7, 98, 14],
       [67, 91, 68, 31],
       [70, 18, 38, 65]])

2. Crea un array 3D de forma (3, 4, 5) con valores enteros del 1 al 60 (sin incluir). Utiliza reshape para convertirlo en un array 2D.

In [ ]:
array_2 = np.random.randint (1,60, (3,4,5))
array_2

array([[[53, 26, 36, 44, 14],
        [22, 54, 29, 34,  4],
        [33, 11, 46, 25,  9],
        [48,  5, 29, 11, 23]],

       [[49, 25, 34, 34, 51],
        [ 8, 59, 47, 58, 23],
        [51, 38, 49, 23, 46],
        [13, 20, 12, 12, 47]],

       [[11, 24, 34, 53,  7],
        [31, 29, 49, 28, 46],
        [35, 19, 16, 43, 37],
        [52, 36, 35, 35, 23]]])

In [ ]:
reshaped_array_2 = np.reshape (array_2, (6,10))
reshaped_array_2

array([[53, 26, 36, 44, 14, 22, 54, 29, 34,  4],
       [33, 11, 46, 25,  9, 48,  5, 29, 11, 23],
       [49, 25, 34, 34, 51,  8, 59, 47, 58, 23],
       [51, 38, 49, 23, 46, 13, 20, 12, 12, 47],
       [11, 24, 34, 53,  7, 31, 29, 49, 28, 46],
       [35, 19, 16, 43, 37, 52, 36, 35, 35, 23]])

3. Crea un array 3D de forma (4, 3, 2) con valores aleatorios entre 0 y 1. Utiliza reshape para convertirlo en un array 2D.

In [ ]:
array_3 = np.random.rand (4,3,2)
array_3

array([[[0.79463835, 0.11675356],
        [0.68153607, 0.30517563],
        [0.14934889, 0.6487142 ]],

       [[0.48957806, 0.87438639],
        [0.37238088, 0.96298892],
        [0.32323312, 0.28665343]],

       [[0.85790159, 0.15271869],
        [0.6064677 , 0.09637331],
        [0.60414664, 0.92731767]],

       [[0.43520413, 0.34427726],
        [0.04768062, 0.37694708],
        [0.83183448, 0.72408611]]])

In [ ]:
reshaped_3 = np.reshape (array_3, (3,8))
reshaped_3

array([[0.79463835, 0.11675356, 0.68153607, 0.30517563, 0.14934889,
        0.6487142 , 0.48957806, 0.87438639],
       [0.37238088, 0.96298892, 0.32323312, 0.28665343, 0.85790159,
        0.15271869, 0.6064677 , 0.09637331],
       [0.60414664, 0.92731767, 0.43520413, 0.34427726, 0.04768062,
        0.37694708, 0.83183448, 0.72408611]])

## Ejercicios con transpose:

4. Utiliza el array 3D del ejercicio 2 de reshape. Utiliza transpose para permutar los ejes y obtener un nuevo array con forma (5, 4, 3).

In [ ]:
array_2

array([[[53, 26, 36, 44, 14],
        [22, 54, 29, 34,  4],
        [33, 11, 46, 25,  9],
        [48,  5, 29, 11, 23]],

       [[49, 25, 34, 34, 51],
        [ 8, 59, 47, 58, 23],
        [51, 38, 49, 23, 46],
        [13, 20, 12, 12, 47]],

       [[11, 24, 34, 53,  7],
        [31, 29, 49, 28, 46],
        [35, 19, 16, 43, 37],
        [52, 36, 35, 35, 23]]])

In [ ]:
transposed_array = np.transpose (array_2)
transposed_array

array([[[53, 49, 11],
        [22,  8, 31],
        [33, 51, 35],
        [48, 13, 52]],

       [[26, 25, 24],
        [54, 59, 29],
        [11, 38, 19],
        [ 5, 20, 36]],

       [[36, 34, 34],
        [29, 47, 49],
        [46, 49, 16],
        [29, 12, 35]],

       [[44, 34, 53],
        [34, 58, 28],
        [25, 23, 43],
        [11, 12, 35]],

       [[14, 51,  7],
        [ 4, 23, 46],
        [ 9, 46, 37],
        [23, 47, 23]]])

5. Utiliza el array 3D del ejercicio 3 de reshape. Utiliza transpose para cambiar el orden de los ejes y obtener un nuevo array con forma (3, 2, 4).

In [ ]:
array_3

array([[[0.79463835, 0.11675356],
        [0.68153607, 0.30517563],
        [0.14934889, 0.6487142 ]],

       [[0.48957806, 0.87438639],
        [0.37238088, 0.96298892],
        [0.32323312, 0.28665343]],

       [[0.85790159, 0.15271869],
        [0.6064677 , 0.09637331],
        [0.60414664, 0.92731767]],

       [[0.43520413, 0.34427726],
        [0.04768062, 0.37694708],
        [0.83183448, 0.72408611]]])

In [ ]:
np.size (array_3)

24

In [ ]:
np.shape (array_3)

(4, 3, 2)

In [ ]:
#al transpose se le indican los índices del shape original
transposed_array2 = np.transpose (array_3, (1,2,0))
transposed_array2

array([[[0.79463835, 0.48957806, 0.85790159, 0.43520413],
        [0.11675356, 0.87438639, 0.15271869, 0.34427726]],

       [[0.68153607, 0.37238088, 0.6064677 , 0.04768062],
        [0.30517563, 0.96298892, 0.09637331, 0.37694708]],

       [[0.14934889, 0.32323312, 0.60414664, 0.83183448],
        [0.6487142 , 0.28665343, 0.92731767, 0.72408611]]])

# Preguntas teóricas:

6. ¿Qué diferencia existe entre el reshape y el transpose?

*reshape* se utiliza para cambiar las dimensiones de un array mientras que *transpose* se utiliza para intercambiar las dimensiones de un array, es decir, toma como argumento un *array* y devuelve una nueva *array* con las dimensiones intercambiadas.

7. ¿Y entre el transpose y el swapaxes?

*transpose* permite permutar todas las dimensiones de un array multidimensional, mientras que *swapaxes* solo intercambia dos dimensiones específicas.

## Funciones Aritméticas y Estadísticas:

1. Crea un array de tres 3D con elementos entre el 0 y 1 de forma (2, 3, 5) cuyos valores solo tengan 1 decimal.

In [21]:
array = np.random.random_sample((2,3,5))
array

array([[[0.42171048, 0.02452492, 0.59040051, 0.74427804, 0.8024387 ],
        [0.93349809, 0.44497035, 0.85650804, 0.09408377, 0.50847907],
        [0.79279295, 0.98715698, 0.7956057 , 0.07549631, 0.41995004]],

       [[0.37416605, 0.66501158, 0.49533009, 0.10884514, 0.3390317 ],
        [0.45909288, 0.42134158, 0.46328817, 0.5649528 , 0.78368882],
        [0.41235799, 0.96883378, 0.99633507, 0.40138025, 0.41827355]]])

2. Crea un array vacío con la misma forma y dimensiones que el array creado anteriormente. Vamos a reemplazar los valores de la matriz vacía que nos acabamos de crear pero basándonos en los valores del primer array bajo las siguientes condiciones:
- Si el valor del array es igual que la media, se reemplaza por "A".
- Si el valor del array es mayor que la media, se reemplaza por "B".
- Si el valor del array es menor que la media, se reemplaza por "C".
- Si el valor es igual que el máximo, se reemplaza por "D".
- Si el valor es igual que el mínimo, se reemplaza por "E".



In [24]:
media = np.mean(array)
max = np.max(array)
min = np.min(array)

In [35]:
array[0][0][0] == media

False

In [26]:
array.shape

(2, 3, 5)

In [27]:
vacio = np.empty_like(array, dtype =str)
vacio

array([[['', '', '', '', ''],
        ['', '', '', '', ''],
        ['', '', '', '', '']],

       [['', '', '', '', ''],
        ['', '', '', '', ''],
        ['', '', '', '', '']]], dtype='<U1')

In [36]:
#cleamos un bucle for para acceder a cada uno de los elementos
for matriz in range (2):
    for fila in range (3):
        for col in range (5):
            if array[matriz][fila][col] == media:
                vacio [matriz][fila][col] = 'A'
            elif array[matriz][fila][col] == max:
                vacio [matriz][fila][col] = 'D'
            elif array[matriz][fila][col] == min:
                vacio [matriz][fila][col] = 'E'
            elif array[matriz][fila][col] > media:
                vacio [matriz][fila][col] = 'B'
            elif array[matriz][fila][col] < media:
                vacio [matriz][fila][col] = 'C'
            

In [37]:
#cleamos un bucle for para acceder a cada uno de los elementos (este bucle podemos utilizarlo para cualquier matriz de cualquier dimension)
for matriz in range (array.shape[0]):
    for fila in range (array.shape[1]):
        for col in range (array.shape[2]):
            if array[matriz][fila][col] == media:
                vacio [matriz][fila][col] = 'A'
            elif array[matriz][fila][col] == max:
                vacio [matriz][fila][col] = 'D'
            elif array[matriz][fila][col] == min:
                vacio [matriz][fila][col] = 'E'
            elif array[matriz][fila][col] > media:
                vacio [matriz][fila][col] = 'B'
            elif array[matriz][fila][col] < media:
                vacio [matriz][fila][col] = 'C'

In [38]:
vacio

array([[['C', 'E', 'B', 'B', 'B'],
        ['B', 'C', 'B', 'C', 'C'],
        ['B', 'B', 'B', 'C', 'C']],

       [['C', 'B', 'C', 'C', 'C'],
        ['C', 'C', 'C', 'B', 'B'],
        ['C', 'B', 'D', 'C', 'C']]], dtype='<U1')