# Creación y Indexación:

In [2]:
import numpy as np

1. Crea un array 1D con 50 valores aleatorio del 10 al 99. Accede a los elementos en las posiciones múltiplos de 5.

In [4]:
array1 = np.random.randint (10,100, (50))
array1

array([48, 19, 53, 53, 89, 89, 20, 16, 38, 16, 94, 95, 68, 44, 20, 20, 27,
       71, 45, 71, 33, 53, 52, 42, 76, 27, 20, 71, 13, 66, 77, 98, 78, 63,
       94, 19, 35, 79, 23, 10, 37, 85, 35, 29, 69, 47, 84, 57, 10, 37])

In [19]:
array1[::5]


array([48, 89, 94, 20, 33, 27, 77, 19, 37, 47])

2. Crea un array 1D con 30 valores del 1 al 20 (ambos incluidos). Utiliza indexación para obtener los elementos en las posiciones impares.

In [16]:
array2 = np.random.randint (1,21,(30))
array2

array([11,  3, 15, 10, 11, 13,  3, 20,  3, 20,  4,  3, 14, 10,  8, 10,  7,
        3,  2, 17,  5,  5,  7, 14,  2, 14, 11,  2,  7,  8])

In [20]:
array2[1::2]

array([ 3, 10, 13, 20, 20,  3, 10, 10,  3, 17,  5, 14, 14,  2,  8])

3. Crea un array 2D de forma (4, 6) con números aleatorios decimales (no deben estar comprendidos solo entre 0 y 1). Accede a la última fila de la matriz. Los decimales deben estar redondeados a 2 decimales.

In [29]:
array3 = np.round(np.random.uniform(1, 9, (4, 6)), decimals=2)
array3

array([[5.79, 1.56, 1.03, 8.06, 7.74, 4.31],
       [7.59, 8.23, 4.12, 5.2 , 5.88, 6.9 ],
       [4.42, 5.34, 3.54, 5.  , 2.5 , 6.15],
       [7.95, 2.03, 7.31, 2.95, 1.64, 3.09]])

In [27]:
array3 [-1]

array([7.36, 8.78, 4.45, 3.82, 2.44, 1.84])

4. Crea un array NumPy 2D de forma (6, 4) con valores decimales entre 0 y 1. Accede a la segunda columna de la matriz. Los números deben estar redondeados a 2 decimales.

In [30]:
array4 = np.round(np.random.rand (6,4), decimals = 2)
array4

array([[0.4 , 0.98, 0.47, 0.46],
       [0.54, 0.47, 0.75, 0.98],
       [0.85, 0.28, 0.39, 0.27],
       [0.08, 0.36, 0.84, 0.03],
       [0.22, 0.8 , 0.71, 0.64],
       [0.24, 0.38, 0.09, 0.06]])

In [33]:
array4[:,1]

array([0.98, 0.47, 0.28, 0.36, 0.8 , 0.38])

5. Crea un array 1D con 30 valores enteros aleatorios entre -50 y 50. Extrae los valores negativos.

In [36]:
array5 = np.random.randint (-50, 51, (30))
array5

array([-12,  20,  14,  24,  32,  39,  15,  45,  27, -45,   0,  19, -24,
        35,  41, -39,  38, -48, -14,  -8, -42, -19,  39,   6, -34,  32,
       -22, -17,  45,  20])

In [38]:
array_negativos = array5[array5 < 0]
array_negativos

array([-12, -45, -24, -39, -48, -14,  -8, -42, -19, -34, -22, -17])

6. Crea un array 1D con 10 valores entre 0 y 1. Redondea los decimales a 2. Obtén los elementos cuyo valor es mayor que 0.5. ¿En que posición/es están esos elementos?

In [40]:
array6 = np.round (np.random.rand(10), decimals=2)
array6

array([0.55, 0.94, 0.89, 0.23, 0.51, 0.97, 0.6 , 0.89, 0.89, 0.23])

In [41]:
array = array6 [array6 >0.5]
array

array([0.55, 0.94, 0.89, 0.51, 0.97, 0.6 , 0.89, 0.89])

7. Crea un array 1D con 40 valores del 1 al 100 (ambos incluidos). Obtén los elementos que son divisibles por 3 y por 4.

In [42]:
array7 = np.random.randint (1,101,(40))
array7

array([ 22,  21, 100,  44,  52,  26,  29,  91,  32,  54,  40,  77,  44,
        10,  33,  63,  49,   8,   4,  68,  97,  83,  11,  18,  84,  51,
        12,  75,  96,  18,  99,  75,  71,  97,  68,  22,  82,  96,  83,
        42])

In [45]:
array_7 = array7 [(array7 %3 == 0) & (array7 &4 == 0)]
array_7

array([33, 18, 51, 75, 96, 18, 99, 75, 96, 42])

8. BONUS: Crea un array 3D de forma (2, 3, 5) y 50 elementos con números enteros entre 0 y 100 (ambos incluidos). Reemplaza los elementos en posiciones múltiplos de 3 por 0.

In [84]:
array8 = np.random.randint (0,101,50)
array8

array([44, 12, 80,  5, 62, 87, 36, 49, 31, 37, 95, 32, 43, 35, 38,  4, 49,
       29, 76,  4, 63, 50, 41, 54, 36, 15, 25,  7, 36, 90, 13, 10, 36, 11,
        5, 58, 92, 67, 55, 57,  3, 16, 17, 80, 12, 59, 72, 18, 70, 51])

In [85]:
array8 [array8 %3 == 0 ] = 0

In [ ]:
#no es posible hacerlo, porque en un array de dimensiones 2,3,5 sólo caben 30 elementos. Podríamos hacerlo con un array de 30 elementos
reshaped_array = np.reshape (array8, (2,3,5))
reshaped_array

# Reshape y Transpose:

1. Crea un array 3D de forma (2, 3, 4) con valores aleatorios entre 1 y 100 (ambos inclusive). Utiliza reshape para convertirlo en un array 2D. Deberás pensar en la forma que es correcta para hacer este cambio.

In [70]:
array_1 = np.random.randint (1,101, (2,3,4))
array_1

array([[[ 9, 71,  9, 92],
        [10, 15, 48, 88],
        [32, 76, 11, 40]],

       [[79, 80, 88, 15],
        [62, 59, 38, 74],
        [67, 30, 37, 71]]])

In [77]:
reshaped_array = np.reshape (array_1, (6,4))
reshaped_array

array([[ 9, 71,  9, 92],
       [10, 15, 48, 88],
       [32, 76, 11, 40],
       [79, 80, 88, 15],
       [62, 59, 38, 74],
       [67, 30, 37, 71]])

In [78]:
#otra forma de hacerlo sería:
reshaped_array = np.reshape (array_1, (-1,4))
reshaped_array

array([[ 9, 71,  9, 92],
       [10, 15, 48, 88],
       [32, 76, 11, 40],
       [79, 80, 88, 15],
       [62, 59, 38, 74],
       [67, 30, 37, 71]])

2. Crea un array 3D de forma (3, 4, 5) con valores enteros del 1 al 60 (sin incluir). Utiliza reshape para convertirlo en un array 2D.

In [88]:
array_2 = np.random.randint (1,60, (3,4,5))
array_2

array([[[26,  3, 58, 24, 57],
        [50, 16,  2, 42, 19],
        [16, 45, 18, 17, 36],
        [ 2, 34, 16, 12, 56]],

       [[37, 58, 46,  6, 41],
        [51, 18, 22,  1,  5],
        [26, 55,  2, 16, 55],
        [47, 39,  5, 32, 30]],

       [[23, 26, 43, 34, 23],
        [20, 20, 42,  9, 33],
        [57, 22, 46, 58, 58],
        [28, 52, 42, 57, 27]]])

In [89]:
reshaped_array_2 = np.reshape (array_2, (6,10))
reshaped_array_2

array([[26,  3, 58, 24, 57, 50, 16,  2, 42, 19],
       [16, 45, 18, 17, 36,  2, 34, 16, 12, 56],
       [37, 58, 46,  6, 41, 51, 18, 22,  1,  5],
       [26, 55,  2, 16, 55, 47, 39,  5, 32, 30],
       [23, 26, 43, 34, 23, 20, 20, 42,  9, 33],
       [57, 22, 46, 58, 58, 28, 52, 42, 57, 27]])

3. Crea un array 3D de forma (4, 3, 2) con valores aleatorios entre 0 y 1. Utiliza reshape para convertirlo en un array 2D.

In [90]:
array_3 = np.random.rand (4,3,2)
array_3

array([[[0.48220652, 0.68691571],
        [0.56134045, 0.40421022],
        [0.68290611, 0.59784142]],

       [[0.9744647 , 0.39526876],
        [0.73116893, 0.17452842],
        [0.28294793, 0.22928928]],

       [[0.54133036, 0.92804078],
        [0.16355309, 0.05231832],
        [0.03919102, 0.95554821]],

       [[0.69564846, 0.13319862],
        [0.74408248, 0.14366771],
        [0.87754125, 0.56242653]]])

In [95]:
reshaped_3 = np.reshape (array_3, (3,8))
reshaped_3

array([[0.48220652, 0.68691571, 0.56134045, 0.40421022, 0.68290611,
        0.59784142, 0.9744647 , 0.39526876],
       [0.73116893, 0.17452842, 0.28294793, 0.22928928, 0.54133036,
        0.92804078, 0.16355309, 0.05231832],
       [0.03919102, 0.95554821, 0.69564846, 0.13319862, 0.74408248,
        0.14366771, 0.87754125, 0.56242653]])

# Ejercicios con transpose:

1. Utiliza el array 3D del ejercicio 2 de reshape. Utiliza transpose para permutar los ejes y obtener un nuevo array con forma (5, 4, 3).

In [97]:
array_2

array([[[26,  3, 58, 24, 57],
        [50, 16,  2, 42, 19],
        [16, 45, 18, 17, 36],
        [ 2, 34, 16, 12, 56]],

       [[37, 58, 46,  6, 41],
        [51, 18, 22,  1,  5],
        [26, 55,  2, 16, 55],
        [47, 39,  5, 32, 30]],

       [[23, 26, 43, 34, 23],
        [20, 20, 42,  9, 33],
        [57, 22, 46, 58, 58],
        [28, 52, 42, 57, 27]]])

In [99]:
transposed_array = np.transpose (array_2)
transposed_array

array([[[26, 37, 23],
        [50, 51, 20],
        [16, 26, 57],
        [ 2, 47, 28]],

       [[ 3, 58, 26],
        [16, 18, 20],
        [45, 55, 22],
        [34, 39, 52]],

       [[58, 46, 43],
        [ 2, 22, 42],
        [18,  2, 46],
        [16,  5, 42]],

       [[24,  6, 34],
        [42,  1,  9],
        [17, 16, 58],
        [12, 32, 57]],

       [[57, 41, 23],
        [19,  5, 33],
        [36, 55, 58],
        [56, 30, 27]]])

5. Utiliza el array 3D del ejercicio 3 de reshape. Utiliza transpose para cambiar el orden de los ejes y obtener un nuevo array con forma (3, 2, 4).

In [100]:
array_3

array([[[0.48220652, 0.68691571],
        [0.56134045, 0.40421022],
        [0.68290611, 0.59784142]],

       [[0.9744647 , 0.39526876],
        [0.73116893, 0.17452842],
        [0.28294793, 0.22928928]],

       [[0.54133036, 0.92804078],
        [0.16355309, 0.05231832],
        [0.03919102, 0.95554821]],

       [[0.69564846, 0.13319862],
        [0.74408248, 0.14366771],
        [0.87754125, 0.56242653]]])

In [103]:
np.size (array_3)

24

In [108]:
np.shape (array_3)

(4, 3, 2)

In [109]:
#al transpose se le indican los índices del shape original
transposed_array2 = np.transpose (array_3, (1,2,0))
transposed_array2

array([[[0.48220652, 0.9744647 , 0.54133036, 0.69564846],
        [0.68691571, 0.39526876, 0.92804078, 0.13319862]],

       [[0.56134045, 0.73116893, 0.16355309, 0.74408248],
        [0.40421022, 0.17452842, 0.05231832, 0.14366771]],

       [[0.68290611, 0.28294793, 0.03919102, 0.87754125],
        [0.59784142, 0.22928928, 0.95554821, 0.56242653]]])