# Pair programming Numpy

## Creación y Indexación:

In [2]:
# en primer lugar, importamos la libreria para poder trabajar con NUMPY
import numpy as np

1. Crea un array 1D con 50 valores aleatorio del 10 al 99. Accede a los elementos en las posiciones múltiplos de 5.

In [3]:
array1 = np.random.randint (10,100, (50))
array1

array([69, 32, 77, 97, 65, 53, 30, 12, 68, 58, 81, 77, 47, 72, 68, 99, 79,
       66, 81, 95, 17, 42, 65, 70, 88, 79, 46, 76, 59, 47, 42, 80, 69, 76,
       61, 80, 77, 61, 88, 41, 88, 14, 53, 70, 54, 60, 17, 18, 65, 94])

In [4]:
array1[::5]


array([69, 53, 81, 99, 17, 79, 42, 80, 88, 60])

2. Crea un array 1D con 30 valores del 1 al 20 (ambos incluidos). Utiliza indexación para obtener los elementos en las posiciones impares.

In [5]:
array2 = np.random.randint (1,21,(30))
array2

array([15,  3, 18, 18, 20,  6,  7,  5,  8,  5,  1, 14,  9, 16, 15,  1, 14,
       15, 13, 11,  5, 15,  6,  9, 19,  8,  8,  4, 18, 17])

In [6]:
array2[1::2]

array([ 3, 18,  6,  5,  5, 14, 16,  1, 15, 11, 15,  9,  8,  4, 17])

3. Crea un array 2D de forma (4, 6) con números aleatorios decimales (no deben estar comprendidos solo entre 0 y 1). Accede a la última fila de la matriz. Los decimales deben estar redondeados a 2 decimales.

In [7]:
array3 = np.round(np.random.uniform(1, 9, (4, 6)), decimals=2)
array3

array([[4.65, 1.46, 7.4 , 8.22, 2.1 , 1.12],
       [1.06, 7.28, 5.76, 1.39, 6.03, 7.12],
       [2.35, 8.64, 7.11, 7.29, 4.03, 4.2 ],
       [3.94, 6.89, 2.14, 8.2 , 2.09, 7.41]])

In [8]:
array3 [-1]

array([3.94, 6.89, 2.14, 8.2 , 2.09, 7.41])

4. Crea un array NumPy 2D de forma (6, 4) con valores decimales entre 0 y 1. Accede a la segunda columna de la matriz. Los números deben estar redondeados a 2 decimales.

In [9]:
array4 = np.round(np.random.rand (6,4), decimals = 2)
array4

array([[0.97, 0.21, 0.56, 0.63],
       [0.51, 0.87, 0.74, 0.99],
       [0.18, 0.3 , 0.88, 0.69],
       [0.89, 0.  , 0.78, 0.84],
       [0.71, 0.54, 0.78, 0.62],
       [0.97, 0.49, 0.54, 0.82]])

In [10]:
array4[:,1]

array([0.21, 0.87, 0.3 , 0.  , 0.54, 0.49])

5. Crea un array 1D con 30 valores enteros aleatorios entre -50 y 50. Extrae los valores negativos.

In [11]:
array5 = np.random.randint (-50, 51, (30))
array5

array([ 26, -48,   3, -27,  -7, -26, -18,  27, -42, -31, -12, -11,   6,
       -18, -26,  19, -12, -19,  40,  49,  42,  16,  24,  40,  11,  18,
        28,  42,  35,  -8])

In [12]:
array_negativos = array5[array5 < 0]
array_negativos

array([-48, -27,  -7, -26, -18, -42, -31, -12, -11, -18, -26, -12, -19,
        -8])

6. Crea un array 1D con 10 valores entre 0 y 1. Redondea los decimales a 2. Obtén los elementos cuyo valor es mayor que 0.5. ¿En que posición/es están esos elementos?

In [13]:
array6 = np.round (np.random.rand(10), decimals=2)
array6

array([0.07, 0.82, 0.19, 0.07, 0.88, 0.58, 0.14, 0.59, 0.18, 0.29])

In [14]:
array = array6 [array6 >0.5]
array

array([0.82, 0.88, 0.58, 0.59])

7. Crea un array 1D con 40 valores del 1 al 100 (ambos incluidos). Obtén los elementos que son divisibles por 3 y por 4.

In [15]:
array7 = np.random.randint (1,101,(40))
array7

array([ 47,  19,  25,  92,  56,  61,  83,   4,  84,  76,  57,  84,  99,
        10,  15,  20,  67,  83,  76,  87,  75, 100,  15,  54,  26,   9,
        94,  73,  99, 100,  51,  19,   8,  94,  41,  79,  53,  67,  76,
        79])

In [16]:
array_7 = array7 [(array7 %3 == 0) & (array7 &4 == 0)]
array_7

array([57, 99, 75,  9, 99, 51])

8. BONUS: Crea un array 3D de forma (2, 3, 5) y 50 elementos con números enteros entre 0 y 100 (ambos incluidos). Reemplaza los elementos en posiciones múltiplos de 3 por 0.

In [17]:
array8 = np.random.randint (0,101,50)
array8

array([ 58,  95,  69,  37,  58,  83,   6,  43,  24, 100,  95,  31,  55,
        43,  83,  20,   6,  60,  95,  62,  83,   0,  39,  72,  66,  45,
        54,  23,  37,  19,  12,   9,  84,  55,  95,  59,  57,  41,  96,
        60,  64,  89,  12,  41,  48,  22,  49,  73,  96,   6])

In [18]:
array8 [array8 %3 == 0 ] = 0

In [ ]:
#no es posible hacerlo, porque en un array de dimensiones 2,3,5 sólo caben 30 elementos. Podríamos hacerlo con un array de 30 elementos
reshaped_array = np.reshape (array8, (2,3,5))
reshaped_array

## Reshape y Transpose:

1. Crea un array 3D de forma (2, 3, 4) con valores aleatorios entre 1 y 100 (ambos inclusive). Utiliza reshape para convertirlo en un array 2D. Deberás pensar en la forma que es correcta para hacer este cambio.

In [21]:
array_1 = np.random.randint (1,101, (2,3,4))
array_1

array([[[46, 75,  6,  8],
        [90, 19, 22, 35],
        [47, 55,  6, 75]],

       [[67,  7, 98, 14],
        [67, 91, 68, 31],
        [70, 18, 38, 65]]])

In [22]:
reshaped_array = np.reshape (array_1, (6,4))
reshaped_array

array([[46, 75,  6,  8],
       [90, 19, 22, 35],
       [47, 55,  6, 75],
       [67,  7, 98, 14],
       [67, 91, 68, 31],
       [70, 18, 38, 65]])

In [23]:
#otra forma de hacerlo sería:
reshaped_array = np.reshape (array_1, (-1,4))
reshaped_array

array([[46, 75,  6,  8],
       [90, 19, 22, 35],
       [47, 55,  6, 75],
       [67,  7, 98, 14],
       [67, 91, 68, 31],
       [70, 18, 38, 65]])

2. Crea un array 3D de forma (3, 4, 5) con valores enteros del 1 al 60 (sin incluir). Utiliza reshape para convertirlo en un array 2D.

In [24]:
array_2 = np.random.randint (1,60, (3,4,5))
array_2

array([[[53, 26, 36, 44, 14],
        [22, 54, 29, 34,  4],
        [33, 11, 46, 25,  9],
        [48,  5, 29, 11, 23]],

       [[49, 25, 34, 34, 51],
        [ 8, 59, 47, 58, 23],
        [51, 38, 49, 23, 46],
        [13, 20, 12, 12, 47]],

       [[11, 24, 34, 53,  7],
        [31, 29, 49, 28, 46],
        [35, 19, 16, 43, 37],
        [52, 36, 35, 35, 23]]])

In [25]:
reshaped_array_2 = np.reshape (array_2, (6,10))
reshaped_array_2

array([[53, 26, 36, 44, 14, 22, 54, 29, 34,  4],
       [33, 11, 46, 25,  9, 48,  5, 29, 11, 23],
       [49, 25, 34, 34, 51,  8, 59, 47, 58, 23],
       [51, 38, 49, 23, 46, 13, 20, 12, 12, 47],
       [11, 24, 34, 53,  7, 31, 29, 49, 28, 46],
       [35, 19, 16, 43, 37, 52, 36, 35, 35, 23]])

3. Crea un array 3D de forma (4, 3, 2) con valores aleatorios entre 0 y 1. Utiliza reshape para convertirlo en un array 2D.

In [26]:
array_3 = np.random.rand (4,3,2)
array_3

array([[[0.79463835, 0.11675356],
        [0.68153607, 0.30517563],
        [0.14934889, 0.6487142 ]],

       [[0.48957806, 0.87438639],
        [0.37238088, 0.96298892],
        [0.32323312, 0.28665343]],

       [[0.85790159, 0.15271869],
        [0.6064677 , 0.09637331],
        [0.60414664, 0.92731767]],

       [[0.43520413, 0.34427726],
        [0.04768062, 0.37694708],
        [0.83183448, 0.72408611]]])

In [27]:
reshaped_3 = np.reshape (array_3, (3,8))
reshaped_3

array([[0.79463835, 0.11675356, 0.68153607, 0.30517563, 0.14934889,
        0.6487142 , 0.48957806, 0.87438639],
       [0.37238088, 0.96298892, 0.32323312, 0.28665343, 0.85790159,
        0.15271869, 0.6064677 , 0.09637331],
       [0.60414664, 0.92731767, 0.43520413, 0.34427726, 0.04768062,
        0.37694708, 0.83183448, 0.72408611]])

## Ejercicios con transpose:

4. Utiliza el array 3D del ejercicio 2 de reshape. Utiliza transpose para permutar los ejes y obtener un nuevo array con forma (5, 4, 3).

In [28]:
array_2

array([[[53, 26, 36, 44, 14],
        [22, 54, 29, 34,  4],
        [33, 11, 46, 25,  9],
        [48,  5, 29, 11, 23]],

       [[49, 25, 34, 34, 51],
        [ 8, 59, 47, 58, 23],
        [51, 38, 49, 23, 46],
        [13, 20, 12, 12, 47]],

       [[11, 24, 34, 53,  7],
        [31, 29, 49, 28, 46],
        [35, 19, 16, 43, 37],
        [52, 36, 35, 35, 23]]])

In [29]:
transposed_array = np.transpose (array_2)
transposed_array

array([[[53, 49, 11],
        [22,  8, 31],
        [33, 51, 35],
        [48, 13, 52]],

       [[26, 25, 24],
        [54, 59, 29],
        [11, 38, 19],
        [ 5, 20, 36]],

       [[36, 34, 34],
        [29, 47, 49],
        [46, 49, 16],
        [29, 12, 35]],

       [[44, 34, 53],
        [34, 58, 28],
        [25, 23, 43],
        [11, 12, 35]],

       [[14, 51,  7],
        [ 4, 23, 46],
        [ 9, 46, 37],
        [23, 47, 23]]])

5. Utiliza el array 3D del ejercicio 3 de reshape. Utiliza transpose para cambiar el orden de los ejes y obtener un nuevo array con forma (3, 2, 4).

In [30]:
array_3

array([[[0.79463835, 0.11675356],
        [0.68153607, 0.30517563],
        [0.14934889, 0.6487142 ]],

       [[0.48957806, 0.87438639],
        [0.37238088, 0.96298892],
        [0.32323312, 0.28665343]],

       [[0.85790159, 0.15271869],
        [0.6064677 , 0.09637331],
        [0.60414664, 0.92731767]],

       [[0.43520413, 0.34427726],
        [0.04768062, 0.37694708],
        [0.83183448, 0.72408611]]])

In [31]:
np.size (array_3)

24

In [32]:
np.shape (array_3)

(4, 3, 2)

In [33]:
#al transpose se le indican los índices del shape original
transposed_array2 = np.transpose (array_3, (1,2,0))
transposed_array2

array([[[0.79463835, 0.48957806, 0.85790159, 0.43520413],
        [0.11675356, 0.87438639, 0.15271869, 0.34427726]],

       [[0.68153607, 0.37238088, 0.6064677 , 0.04768062],
        [0.30517563, 0.96298892, 0.09637331, 0.37694708]],

       [[0.14934889, 0.32323312, 0.60414664, 0.83183448],
        [0.6487142 , 0.28665343, 0.92731767, 0.72408611]]])

# Preguntas teóricas:

6. ¿Qué diferencia existe entre el reshape y el transpose?

*reshape* se utiliza para cambiar las dimensiones de un array mientras que *transpose* se utiliza para intercambiar las dimensiones de un array, es decir, toma como argumento un *array* y devuelve una nueva *array* con las dimensiones intercambiadas.

7. ¿Y entre el transpose y el swapaxes?

*transpose* permite permutar todas las dimensiones de un array multidimensional, mientras que *swapaxes* solo intercambia dos dimensiones específicas.

## Funciones Aritméticas y Estadísticas:

1. Crea un array de tres 3D con elementos entre el 0 y 1 de forma (2, 3, 5) cuyos valores solo tengan 1 decimal.

2. Crea un array vacío con la misma forma y dimensiones que el array creado anteriormente. Vamos a reemplazar los valores de la matriz vacía que nos acabamos de crear pero basándonos en los valores del primer array bajo las siguientes condiciones:
- Si el valor del array es igual que la media, se reemplaza por "A".
- Si el valor del array es mayor que la media, se reemplaza por "B".
- Si el valor del array es menor que la media, se reemplaza por "C".
- Si el valor es igual que el máximo, se reemplaza por "D".
- Si el valor es igual que el mínimo, se reemplaza por "E".



In [ ]:
# a modo de ejemplo. Si tenemos el siguiente array
[[[0.4, 0.7, 0.2, 0.9, 0.2],
    [0.1, 0.9, 0.6, 0.1, 0.2],
    [1. , 0.2, 0.1, 0.8, 0.3]],

[[0. , 0.3, 0.4, 0.5, 0.1],
    [0.5, 0.7, 0.9, 0. , 0.8],
    [0.5, 0.3, 0.5, 0.8, 0.1]]])

# sabiendo que la media es 0.4 y el máximo es 1.0 y el mínimo es 0.0

# nuestro array vacío debería quedar como este: 
([[["A", "B", "C", "B", "C"],
    ["C", "B", "B", "C", "C"],
    ["D" , "C", "C", "B", "C"]],

[["E" , "C", "A", "B", "C"],
    ["B", "B","B", "E" , "B"],
    ["B", "C", "B", "B", "C"]]])