# Pair programming Numpy

## Creación y Indexación:

In [2]:
# en primer lugar, importamos la libreria para poder trabajar con NUMPY
import numpy as np

1. Crea un array 1D con 50 valores aleatorio del 10 al 99. Accede a los elementos en las posiciones múltiplos de 5.

In [3]:
array1 = np.random.randint (10,100, (50))
array1

array([62, 52, 33, 36, 71, 99, 43, 87, 19, 78, 29, 39, 22, 27, 34, 73, 89,
       31, 32, 13, 52, 37, 67, 22, 46, 28, 67, 85, 46, 85, 80, 30, 79, 73,
       14, 23, 77, 70, 20, 72, 90, 49, 36, 56, 31, 91, 48, 52, 93, 10])

In [4]:
array1[::5]


array([62, 99, 29, 73, 52, 28, 80, 23, 90, 91])

2. Crea un array 1D con 30 valores del 1 al 20 (ambos incluidos). Utiliza indexación para obtener los elementos en las posiciones impares.

In [5]:
array2 = np.random.randint (1,21,(30))
array2

array([13, 11,  4, 18, 12, 15,  5,  2,  5, 16, 11, 16, 10,  8,  5,  2, 15,
        4, 18,  7,  4,  8,  5,  5,  7,  7, 16, 15,  4,  7])

In [6]:
array2[1::2]

array([11, 18, 15,  2, 16, 16,  8,  2,  4,  7,  8,  5,  7, 15,  7])

3. Crea un array 2D de forma (4, 6) con números aleatorios decimales (no deben estar comprendidos solo entre 0 y 1). Accede a la última fila de la matriz. Los decimales deben estar redondeados a 2 decimales.

In [7]:
array3 = np.round(np.random.uniform(1, 9, (4, 6)), decimals=2)
array3

array([[4.75, 5.36, 8.93, 4.88, 6.28, 2.85],
       [3.83, 1.55, 8.08, 6.17, 3.02, 2.28],
       [2.34, 6.11, 1.75, 2.95, 5.22, 8.54],
       [7.04, 1.19, 3.71, 3.36, 4.62, 4.04]])

In [8]:
array3 [-1]

array([7.04, 1.19, 3.71, 3.36, 4.62, 4.04])

4. Crea un array NumPy 2D de forma (6, 4) con valores decimales entre 0 y 1. Accede a la segunda columna de la matriz. Los números deben estar redondeados a 2 decimales.

In [9]:
array4 = np.round(np.random.rand (6,4), decimals = 2)
array4

array([[0.73, 0.72, 0.53, 0.35],
       [0.83, 0.3 , 0.96, 0.39],
       [0.93, 0.46, 0.32, 0.04],
       [0.41, 0.99, 0.08, 0.11],
       [0.18, 0.61, 0.62, 0.98],
       [0.54, 0.41, 0.24, 0.27]])

In [10]:
array4[:,1]

array([0.72, 0.3 , 0.46, 0.99, 0.61, 0.41])

5. Crea un array 1D con 30 valores enteros aleatorios entre -50 y 50. Extrae los valores negativos.

In [11]:
array5 = np.random.randint (-50, 51, (30))
array5

array([ -7,  14, -28, -25,   3,  37, -36,  21,   3, -33, -48, -24,  10,
        30,   6,  43,  25, -49, -45, -30,   9,  15, -28, -30, -33, -20,
       -32,  16, -25, -29])

In [12]:
array_negativos = array5[array5 < 0]
array_negativos

array([ -7, -28, -25, -36, -33, -48, -24, -49, -45, -30, -28, -30, -33,
       -20, -32, -25, -29])

6. Crea un array 1D con 10 valores entre 0 y 1. Redondea los decimales a 2. Obtén los elementos cuyo valor es mayor que 0.5. ¿En que posición/es están esos elementos?

In [13]:
array6 = np.round (np.random.rand(10), decimals=2)
array6

array([0.58, 0.1 , 0.24, 0.78, 0.77, 0.58, 0.45, 0.76, 0.75, 0.47])

In [14]:
# los elementos están en las posiciones 1, 3, 4, 6, 7, 8, y 9
array = array6 [array6 >0.5]
array

array([0.58, 0.78, 0.77, 0.58, 0.76, 0.75])

7. Crea un array 1D con 40 valores del 1 al 100 (ambos incluidos). Obtén los elementos que son divisibles por 3 y por 4.

In [15]:
array7 = np.random.randint (1,101,(40))
array7

array([ 75,  65,  27,  33,  26,  91,  62,  11,  90,  21,  98,  25,  88,
        19,  55,  81,  68,  37,  75,  55,   3,  94,  14,  25,  62,  13,
        69, 100,  46,  58,  25,  15,  24,  67,  56,  14,  78,  48,  91,
        17])

In [16]:
array_7 = array7 [(array7 %3 == 0) & (array7 &4 == 0)]
array_7

array([75, 27, 33, 90, 81, 75,  3, 24, 48])

8. BONUS: Crea un array 3D de forma (2, 3, 5) y 30 elementos con números enteros entre 0 y 100 (ambos incluidos). Reemplaza los elementos en posiciones múltiplos de 3 por 0.

In [33]:
array8 = np.random.randint (0,101,30)
array8

array([17, 18, 12, 68,  2, 61, 55, 81, 21, 93, 21, 36, 58, 50,  5, 28, 70,
       61, 19, 46, 25, 81, 78, 82, 58, 75, 51, 90, 80, 30])

In [34]:
array8 [array8 %3 == 0 ] = 0
array8

array([17,  0,  0, 68,  2, 61, 55,  0,  0,  0,  0,  0, 58, 50,  5, 28, 70,
       61, 19, 46, 25,  0,  0, 82, 58,  0,  0,  0, 80,  0])

In [35]:
reshaped_array = np.reshape (array8, (2,3,5))
reshaped_array

array([[[17,  0,  0, 68,  2],
        [61, 55,  0,  0,  0],
        [ 0,  0, 58, 50,  5]],

       [[28, 70, 61, 19, 46],
        [25,  0,  0, 82, 58],
        [ 0,  0,  0, 80,  0]]])

## Reshape y Transpose:

1. Crea un array 3D de forma (2, 3, 4) con valores aleatorios entre 1 y 100 (ambos inclusive). Utiliza reshape para convertirlo en un array 2D. Deberás pensar en la forma que es correcta para hacer este cambio.

In [ ]:
array_1 = np.random.randint (1,101, (2,3,4))
array_1

array([[[46, 75,  6,  8],
        [90, 19, 22, 35],
        [47, 55,  6, 75]],

       [[67,  7, 98, 14],
        [67, 91, 68, 31],
        [70, 18, 38, 65]]])

In [ ]:
reshaped_array = np.reshape (array_1, (6,4))
reshaped_array

array([[46, 75,  6,  8],
       [90, 19, 22, 35],
       [47, 55,  6, 75],
       [67,  7, 98, 14],
       [67, 91, 68, 31],
       [70, 18, 38, 65]])

In [ ]:
#otra forma de hacerlo sería:
reshaped_array = np.reshape (array_1, (-1,4))
reshaped_array

array([[46, 75,  6,  8],
       [90, 19, 22, 35],
       [47, 55,  6, 75],
       [67,  7, 98, 14],
       [67, 91, 68, 31],
       [70, 18, 38, 65]])

2. Crea un array 3D de forma (3, 4, 5) con valores enteros del 1 al 60 (sin incluir). Utiliza reshape para convertirlo en un array 2D.

In [ ]:
array_2 = np.random.randint (1,60, (3,4,5))
array_2

array([[[53, 26, 36, 44, 14],
        [22, 54, 29, 34,  4],
        [33, 11, 46, 25,  9],
        [48,  5, 29, 11, 23]],

       [[49, 25, 34, 34, 51],
        [ 8, 59, 47, 58, 23],
        [51, 38, 49, 23, 46],
        [13, 20, 12, 12, 47]],

       [[11, 24, 34, 53,  7],
        [31, 29, 49, 28, 46],
        [35, 19, 16, 43, 37],
        [52, 36, 35, 35, 23]]])

In [ ]:
reshaped_array_2 = np.reshape (array_2, (6,10))
reshaped_array_2

array([[53, 26, 36, 44, 14, 22, 54, 29, 34,  4],
       [33, 11, 46, 25,  9, 48,  5, 29, 11, 23],
       [49, 25, 34, 34, 51,  8, 59, 47, 58, 23],
       [51, 38, 49, 23, 46, 13, 20, 12, 12, 47],
       [11, 24, 34, 53,  7, 31, 29, 49, 28, 46],
       [35, 19, 16, 43, 37, 52, 36, 35, 35, 23]])

3. Crea un array 3D de forma (4, 3, 2) con valores aleatorios entre 0 y 1. Utiliza reshape para convertirlo en un array 2D.

In [ ]:
array_3 = np.random.rand (4,3,2)
array_3

array([[[0.79463835, 0.11675356],
        [0.68153607, 0.30517563],
        [0.14934889, 0.6487142 ]],

       [[0.48957806, 0.87438639],
        [0.37238088, 0.96298892],
        [0.32323312, 0.28665343]],

       [[0.85790159, 0.15271869],
        [0.6064677 , 0.09637331],
        [0.60414664, 0.92731767]],

       [[0.43520413, 0.34427726],
        [0.04768062, 0.37694708],
        [0.83183448, 0.72408611]]])

In [ ]:
reshaped_3 = np.reshape (array_3, (3,8))
reshaped_3

array([[0.79463835, 0.11675356, 0.68153607, 0.30517563, 0.14934889,
        0.6487142 , 0.48957806, 0.87438639],
       [0.37238088, 0.96298892, 0.32323312, 0.28665343, 0.85790159,
        0.15271869, 0.6064677 , 0.09637331],
       [0.60414664, 0.92731767, 0.43520413, 0.34427726, 0.04768062,
        0.37694708, 0.83183448, 0.72408611]])

## Ejercicios con transpose:

4. Utiliza el array 3D del ejercicio 2 de reshape. Utiliza transpose para permutar los ejes y obtener un nuevo array con forma (5, 4, 3).

In [ ]:
array_2

array([[[53, 26, 36, 44, 14],
        [22, 54, 29, 34,  4],
        [33, 11, 46, 25,  9],
        [48,  5, 29, 11, 23]],

       [[49, 25, 34, 34, 51],
        [ 8, 59, 47, 58, 23],
        [51, 38, 49, 23, 46],
        [13, 20, 12, 12, 47]],

       [[11, 24, 34, 53,  7],
        [31, 29, 49, 28, 46],
        [35, 19, 16, 43, 37],
        [52, 36, 35, 35, 23]]])

In [ ]:
transposed_array = np.transpose (array_2)
transposed_array

array([[[53, 49, 11],
        [22,  8, 31],
        [33, 51, 35],
        [48, 13, 52]],

       [[26, 25, 24],
        [54, 59, 29],
        [11, 38, 19],
        [ 5, 20, 36]],

       [[36, 34, 34],
        [29, 47, 49],
        [46, 49, 16],
        [29, 12, 35]],

       [[44, 34, 53],
        [34, 58, 28],
        [25, 23, 43],
        [11, 12, 35]],

       [[14, 51,  7],
        [ 4, 23, 46],
        [ 9, 46, 37],
        [23, 47, 23]]])

5. Utiliza el array 3D del ejercicio 3 de reshape. Utiliza transpose para cambiar el orden de los ejes y obtener un nuevo array con forma (3, 2, 4).

In [ ]:
array_3

array([[[0.79463835, 0.11675356],
        [0.68153607, 0.30517563],
        [0.14934889, 0.6487142 ]],

       [[0.48957806, 0.87438639],
        [0.37238088, 0.96298892],
        [0.32323312, 0.28665343]],

       [[0.85790159, 0.15271869],
        [0.6064677 , 0.09637331],
        [0.60414664, 0.92731767]],

       [[0.43520413, 0.34427726],
        [0.04768062, 0.37694708],
        [0.83183448, 0.72408611]]])

In [ ]:
np.size (array_3)

24

In [ ]:
np.shape (array_3)

(4, 3, 2)

In [ ]:
#al transpose se le indican los índices del shape original
transposed_array2 = np.transpose (array_3, (1,2,0))
transposed_array2

array([[[0.79463835, 0.48957806, 0.85790159, 0.43520413],
        [0.11675356, 0.87438639, 0.15271869, 0.34427726]],

       [[0.68153607, 0.37238088, 0.6064677 , 0.04768062],
        [0.30517563, 0.96298892, 0.09637331, 0.37694708]],

       [[0.14934889, 0.32323312, 0.60414664, 0.83183448],
        [0.6487142 , 0.28665343, 0.92731767, 0.72408611]]])

# Preguntas teóricas:

6. ¿Qué diferencia existe entre el reshape y el transpose?

*reshape* se utiliza para cambiar las dimensiones de un array mientras que *transpose* se utiliza para intercambiar las dimensiones de un array, es decir, toma como argumento un *array* y devuelve una nueva *array* con las dimensiones intercambiadas.

7. ¿Y entre el transpose y el swapaxes?

*transpose* permite permutar todas las dimensiones de un array multidimensional, mientras que *swapaxes* solo intercambia dos dimensiones específicas.

## Funciones Aritméticas y Estadísticas:

1. Crea un array de tres 3D con elementos entre el 0 y 1 de forma (2, 3, 5) cuyos valores solo tengan 1 decimal.

In [ ]:
array = np.random.random_sample((2,3,5))
array

array([[[0.42171048, 0.02452492, 0.59040051, 0.74427804, 0.8024387 ],
        [0.93349809, 0.44497035, 0.85650804, 0.09408377, 0.50847907],
        [0.79279295, 0.98715698, 0.7956057 , 0.07549631, 0.41995004]],

       [[0.37416605, 0.66501158, 0.49533009, 0.10884514, 0.3390317 ],
        [0.45909288, 0.42134158, 0.46328817, 0.5649528 , 0.78368882],
        [0.41235799, 0.96883378, 0.99633507, 0.40138025, 0.41827355]]])

2. Crea un array vacío con la misma forma y dimensiones que el array creado anteriormente. Vamos a reemplazar los valores de la matriz vacía que nos acabamos de crear pero basándonos en los valores del primer array bajo las siguientes condiciones:
- Si el valor del array es igual que la media, se reemplaza por "A".
- Si el valor del array es mayor que la media, se reemplaza por "B".
- Si el valor del array es menor que la media, se reemplaza por "C".
- Si el valor es igual que el máximo, se reemplaza por "D".
- Si el valor es igual que el mínimo, se reemplaza por "E".



In [ ]:
media = np.mean(array)
max = np.max(array)
min = np.min(array)

In [ ]:
array[0][0][0] == media

False

In [ ]:
array.shape

(2, 3, 5)

In [ ]:
vacio = np.empty_like(array, dtype =str)
vacio

array([[['', '', '', '', ''],
        ['', '', '', '', ''],
        ['', '', '', '', '']],

       [['', '', '', '', ''],
        ['', '', '', '', ''],
        ['', '', '', '', '']]], dtype='<U1')

In [ ]:
#cleamos un bucle for para acceder a cada uno de los elementos
for matriz in range (2):
    for fila in range (3):
        for col in range (5):
            if array[matriz][fila][col] == media:
                vacio [matriz][fila][col] = 'A'
            elif array[matriz][fila][col] == max:
                vacio [matriz][fila][col] = 'D'
            elif array[matriz][fila][col] == min:
                vacio [matriz][fila][col] = 'E'
            elif array[matriz][fila][col] > media:
                vacio [matriz][fila][col] = 'B'
            elif array[matriz][fila][col] < media:
                vacio [matriz][fila][col] = 'C'
            

In [ ]:
#cleamos un bucle for para acceder a cada uno de los elementos (este bucle podemos utilizarlo para cualquier matriz de cualquier dimension)
for matriz in range (array.shape[0]):
    for fila in range (array.shape[1]):
        for col in range (array.shape[2]):
            if array[matriz][fila][col] == media:
                vacio [matriz][fila][col] = 'A'
            elif array[matriz][fila][col] == max:
                vacio [matriz][fila][col] = 'D'
            elif array[matriz][fila][col] == min:
                vacio [matriz][fila][col] = 'E'
            elif array[matriz][fila][col] > media:
                vacio [matriz][fila][col] = 'B'
            elif array[matriz][fila][col] < media:
                vacio [matriz][fila][col] = 'C'

In [ ]:
vacio

array([[['C', 'E', 'B', 'B', 'B'],
        ['B', 'C', 'B', 'C', 'C'],
        ['B', 'B', 'B', 'C', 'C']],

       [['C', 'B', 'C', 'C', 'C'],
        ['C', 'C', 'C', 'B', 'B'],
        ['C', 'B', 'D', 'C', 'C']]], dtype='<U1')